import img1 from '../../images/brand/card4.jpg';
import img2 from '../../images/brand/card2.jpg';

export const solution = {
  id: 'solution',
  btn: true,
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Primary Sign of Stroke',
  topLineDark: false,
  headline: 'BioMAG Physiotherapy Profers Solution for Stroke Crisis and Prevention',
  description1: '1.) Fast Breathing: Due to shortage of blood to the lungs',
  description2: '2.) Coughing and Sneezing: Fluid build up in the lungs, congestion, air passage blocked.',
  description3: '3.) Swelling of legs: Excess fluid in the body tissue. Excess salt in the body.',
  description4: '4.) Tiredness and Fatigue: The heart cannot pump enough blood to meet the need of the body tissue; body diverts blood away from less vital organs, particularly muscles in the limb and sends it to the heart and brain.',
  description5: '5.) Lack of Appetite: The digestive system receives less blood. There is a feeling of being full or sick to the stomach.',
  description6: '6.) Poor blood supply to the hands causing numbness.',
  description7: '7.) Less blood supply to the legs, causing cold, swelling and heaviness.',
  description8: '8.) Total blockage of blood vessels leads to stroke.',
  description9: '9.) Dizziness: Due to less blood supply to the brain.',
  description10: '10.) Inability to maintain balance due to muscle weakness.',
  description11: '11.) Biting sensation is felt at the palm or fingers.',
  description12: '12.) Involutary muscle reaction or spasm can occur (Nerve reflex action).',
  description13: '13.) Half of the body becomes heavy.',
  description14: '14.) Sharp pain is felt in the left side of the heart called (angina pectoris).',
  description15: '15.) Blood pressure becomes high.',
  description16: '16.) Constipation set in due to inadequate intake of water and fluid.',
  description17: '17.) Sleepless night can occur as a result of bio: Chemical in balance or coherence.',
  description18: '18.) A serious life threatening condition can set in.',
  description19: '19.) This can lead to death.',
  topLine2: 'Four major obstructed pressure points',
  _description1: '1.) Temporal Arteries: Side of the tempo',
  _description2: '2.) Carotid Arteries: Side of the neck',
  _description3: '3.) Sub clavicle Arteries: Shoulder down to the Humerus',
  _description4: '4.) Femoral: Side of the thigh',
  imgStart: false,
  img: img1,
  alt: 'alt',
  dark: true,
  primary: true,
  darkText: false,
  justifyEnd: false,
  animateIn: 'bounceInLeft',
  animateOut: 'bounceOutLeft'
}

export const homeObjOne = {
  id: 'discover',
  btn: true,
  lightBg: false,
  lightText: false,
  lightTextDesc: true,
  topLine: 'Biomag Global Physiotherapy',
  topLineDark: false,
  headline: 'Health Benefit of Biomagnetic Energy Pack/Card',
  description: `It stimulates our natural immune function to kill viruses and bacteria, and enhances cell nutrient absorption and waste detoxification.
                Reduces the harmful effects of EMF (Electro Magnetic Field) from cell phones, computers, wifi, etc...`,
  imgStart: false,
  img: img1,
  alt: 'alt',
  dark: true,
  primary: true,
  darkText: false,
  justifyEnd: false,
  animateIn: 'bounceInLeft',
  animateOut: 'bounceOutLeft'
}

export const homeObjTwo = {
  id: 'signin',
  btn: false,
  lightBg: true,
  lightText: true,
  lightTextDesc: false,
  topLine: 'Biomag Global Physiotherapy',
  topLineDark: true,
  headline: 'How to use the Biomagnetic Energy Pack/Card',
  description: `The  energy pack can be placed on refrigerator, freezers, packs of sachet or bottled water, it can be connected to your water supply/tap
                in your home as it energises and alkalise anything it comes in contact with through the generation of scalar energy. The card can be worn
                as an ID card or placed on any part of the body where there is pain. It has been proven to be an effective pain reliever.`,
  imgStart: true,
  img: img2,
  alt: 'alt',
  dark: true,
  primary: false,
  darkText: true,
  justifyEnd: true,
  animateIn: 'bounceInRight',
  animateOut: 'bounceOutRight'
}